###########
# site.url, site.title

title: 'EBRD Labs'
tagline: 'Helping Jon'

## note: 
#  use site.path in your templates to make it work for both protocols e.g. http and https
#  use site.url only inside the web feed template (e.g. requires full url incl. protocol)
#path: /jekyll-bootstrap-theme
path: /
url: https://ebrdlabs.co.uk

pages: ./_pages

site.github.repo: https://github.com/jonstones
########
# more settings

markdown: kramdown

sass:
  sass_dir: assets/css
  style:    expanded

exclude:
- README.md

safe: true
lsi: false

plugins:
  - jekyll-pages-directory
  

